const WORD_PAIRS = [
  { crew: 'Ocean', imposter: 'River', blocklist: { crew: ['sea', 'wave', 'tide', 'marine', 'nautical', 'saltwater', 'beach', 'coast'], imposter: ['stream', 'brook', 'current', 'flowing', 'bank'] } },
  { crew: 'Pizza', imposter: 'Flatbread', blocklist: { crew: ['pepperoni', 'mozzarella', 'slice', 'crust', 'italian food'], imposter: ['pita', 'naan', 'unleavened', 'tortilla'] } },
  { crew: 'Guitar', imposter: 'Violin', blocklist: { crew: ['strum', 'chord', 'fret', 'pluck', 'pick', 'acoustic', 'electric'], imposter: ['bow', 'fiddle', 'string', 'classical'] } },
  { crew: 'Diamond', imposter: 'Crystal', blocklist: { crew: ['gem', 'jewel', 'ring', 'carat', 'sparkle'], imposter: ['quartz', 'glass', 'mineral', 'clear'] } },
  { crew: 'Castle', imposter: 'Mansion', blocklist: { crew: ['knight', 'moat', 'medieval', 'tower', 'fortress', 'dungeon'], imposter: ['estate', 'villa', 'luxury home', 'butler'] } },
  { crew: 'Volcano', imposter: 'Geyser', blocklist: { crew: ['lava', 'magma', 'eruption', 'ash', 'molten'], imposter: ['hot spring', 'yellowstone', 'steam', 'boiling water'] } },
  { crew: 'Submarine', imposter: 'Boat', blocklist: { crew: ['underwater', 'periscope', 'torpedo', 'navy', 'submerge'], imposter: ['sail', 'float', 'vessel', 'captain', 'water vehicle'] } },
  { crew: 'Hospital', imposter: 'Clinic', blocklist: { crew: ['emergency', 'surgery', 'nurse', 'doctor', 'medical', 'icu'], imposter: ['appointment', 'checkup', 'outpatient', 'small medical'] } },
  { crew: 'Tornado', imposter: 'Hurricane', blocklist: { crew: ['funnel', 'twister', 'cyclone', 'spinning wind'], imposter: ['tropical storm', 'category', 'eye of storm', 'coastal'] } },
  { crew: 'Library', imposter: 'Bookstore', blocklist: { crew: ['borrow', 'return', 'librarian', 'overdue', 'free books'], imposter: ['buy', 'purchase', 'shelf', 'bestseller', 'sell books'] } },
  { crew: 'Astronaut', imposter: 'Pilot', blocklist: { crew: ['space', 'nasa', 'zero gravity', 'orbit', 'moon'], imposter: ['cockpit', 'altitude', 'runway', 'airplane'] } },
  { crew: 'Chocolate', imposter: 'Caramel', blocklist: { crew: ['cocoa', 'cacao', 'dark chocolate', 'milk chocolate', 'brownie'], imposter: ['toffee', 'butterscotch', 'golden', 'chewy candy'] } },
  { crew: 'Elephant', imposter: 'Rhinoceros', blocklist: { crew: ['trunk', 'tusk', 'ivory', 'large mammal africa', 'grey animal'], imposter: ['horn', 'thick skin', 'rhino', 'savanna'] } },
  { crew: 'Waterfall', imposter: 'Fountain', blocklist: { crew: ['niagara', 'cliff', 'natural water fall', 'cascade'], imposter: ['park', 'decoration', 'plaza', 'man-made water'] } },
  { crew: 'Passport', imposter: 'License', blocklist: { crew: ['visa', 'border', 'travel document', 'country', 'immigration'], imposter: ['driving', 'id card', 'photo id', 'permit'] } },
  { crew: 'Campfire', imposter: 'Bonfire', blocklist: { crew: ['tent', 'camping', 'marshmallow', 'smores', 'outdoor fire'], imposter: ['bonfire night', 'festival fire', 'celebration fire', 'large fire'] } },
  { crew: 'Skateboard', imposter: 'Surfboard', blocklist: { crew: ['kickflip', 'skate park', 'halfpipe', 'street skating', 'wheels board'], imposter: ['wave', 'surfing', 'ocean sport', 'paddling'] } },
  { crew: 'Microwave', imposter: 'Oven', blocklist: { crew: ['radiation', 'zap food', 'beep', 'rotating plate', 'quick heat'], imposter: ['bake', 'preheat', 'roast', 'oven temperature'] } },
  { crew: 'Symphony', imposter: 'Concert', blocklist: { crew: ['orchestra', 'conductor', 'classical music', 'philharmonic'], imposter: ['rock concert', 'live music', 'performer', 'venue', 'audience'] } },
  { crew: 'Pyramid', imposter: 'Triangle', blocklist: { crew: ['egypt', 'pharaoh', 'ancient', 'giza', 'tomb'], imposter: ['shape', 'geometry', 'three sides', 'polygon'] } },
  { crew: 'Mirror', imposter: 'Window', blocklist: { crew: ['reflection', 'reflect', 'self image', 'vanity'], imposter: ['glass pane', 'see through', 'view outside', 'curtain'] } },
  { crew: 'Compass', imposter: 'GPS', blocklist: { crew: ['north', 'south', 'magnetic needle', 'direction finding', 'cardinal'], imposter: ['satellite', 'navigation app', 'digital map', 'coordinates'] } },
  { crew: 'Coffee', imposter: 'Tea', blocklist: { crew: ['espresso', 'latte', 'caffeine drink', 'barista', 'roasted beans'], imposter: ['brew', 'kettle', 'bags', 'herbal', 'green tea'] } },
  { crew: 'Museum', imposter: 'Gallery', blocklist: { crew: ['artifact', 'exhibit', 'history', 'ancient display'], imposter: ['painting', 'artwork display', 'modern art', 'artist'] } },
  { crew: 'Prison', imposter: 'School', blocklist: { crew: ['cell', 'inmate', 'bars', 'warden', 'jail', 'sentence'], imposter: ['classroom', 'teacher', 'student', 'homework', 'lesson'] } },
  { crew: 'Telescope', imposter: 'Microscope', blocklist: { crew: ['stars', 'astronomy', 'look far away', 'night sky'], imposter: ['bacteria', 'tiny things', 'lab instrument', 'zoomed in'] } },
  { crew: 'Bank', imposter: 'Wallet', blocklist: { crew: ['vault', 'teller', 'account', 'deposit', 'financial institution'], imposter: ['pocket', 'leather', 'carry money', 'billfold'] } },
  { crew: 'Lighthouse', imposter: 'Streetlight', blocklist: { crew: ['beacon', 'coast guard', 'sailor', 'shipping lane', 'foghorn'], imposter: ['road', 'urban light', 'lamp post', 'city'] } },
  { crew: 'Parachute', imposter: 'Umbrella', blocklist: { crew: ['skydiving', 'jump from plane', 'deploy', 'freefall'], imposter: ['rain', 'shelter from rain', 'canopy', 'handle'] } },
  { crew: 'Fireplace', imposter: 'Radiator', blocklist: { crew: ['chimney', 'mantle', 'wood burning', 'crackling fire', 'hearth'], imposter: ['central heating', 'boiler', 'metal heat', 'radiator fins'] } },
];

module.exports = { WORD_PAIRS };
